[phases.setup]
nixPkgs = ["bun", "nodejs"]

[phases.install]
cmds = [
  "bun install",
  "bun add -D lightningcss-linux-x64-gnu"
]

[phases.build]
cmds = ["bun run build"]

[start]
cmd = "bun run start"
